### ISSUE TITLE
fpcalc missing?

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#32]
I don't recall having to install this manually previously?

`/usr/bin/fpclac`is the path that is in my setup for the AcousticID fingerprint calculator, but its now not found "Please select a valid fpcalc executable" is displayed, with the offer to download it.

**Comment by mikenye** [comment]
The path has changed, `fpcalc` is located in `/usr/local/bin/fpcalc`.

This is because I'm now building it from source (<https://github.com/mikenye/docker-picard/blob/b5276a39cdbd136275842657fd957ae74e5ce094/Dockerfile#L92>), so by default the prefix is `/usr/local`.

If Picard by default looks for fpcalc in /usr/bin, I can either change the prefix so the binary that gets built in the image ends up in /usr/bin, or I can put a symlink in place, or we can attempt to modify the configuration of Picard.

I'm tempted to go the symlink approach, because:

* It's the easiest
* Putting user-compiled stuff in /usr/bin is usually not a good idea because it can interfere with binaries managed by the underlying OS's package manager
* Modifying Picard may break existing users

What do you think?

**Comment by techie2000** [comment]
Symlink is in keeping with the KISS approach I generally favour :)

**Comment by mikenye** [comment]
Symlink added, image is building. Should be ready in about 30 mins.

**Comment by techie2000** [comment]
Downloaded/installed and seen to work as expected.

Many thanks once again.
